#gray triggerfish size/trip/seasonal quota/acl table - COMMERCIAL
mh_finalgtf <- mh_final%>%
  filter(FMP == "SNAPPER-GROUPER FISHERY OF THE SOUTH ATLANTIC REGION",
         COMMON_NAME_USE == "TRIGGERFISH, GRAY",
         MANAGEMENT_TYPE_USE %in% c("FISHING SEASON", "MINIMUM SIZE LIMIT", "TRIP LIMIT", "QUOTA", "ACL", "CLOSURE"),
         SECTOR_USE == "COMMERCIAL")%>%
  select(CLUSTER, STATUS_TYPE, MANAGEMENT_TYPE_USE, MANAGEMENT_STATUS_USE, SECTOR, SUBSECTOR_USE, ZONE, SECTOR_ID, EFFECTIVE_DATE, INEFFECTIVE_DATE, 
         START_DAY, START_MONTH, START_YEAR, START_DATE, END_DAY, END_MONTH, END_YEAR)


View(mh_finalgtf)

#gray triggerfish size/BAG/seasonal quota/acl table - RECREATIONAL
mh_finalgtf <- mh_final%>%
  filter(FMP == "SNAPPER-GROUPER FISHERY OF THE SOUTH ATLANTIC REGION",
         COMMON_NAME_USE == "TRIGGERFISH, GRAY",
         MANAGEMENT_TYPE_USE %in% c("FISHING SEASON", "MINIMUM SIZE LIMIT", "BAG LIMIT", "QUOTA", "ACL", "CLOSURE"),
         SECTOR_USE == "RECREATIONAL")%>%
  select(CLUSTER, STATUS_TYPE, MANAGEMENT_TYPE_USE, MANAGEMENT_STATUS_USE, SECTOR, SUBSECTOR_USE, ZONE, SECTOR_ID, EFFECTIVE_DATE, INEFFECTIVE_DATE, 
         START_DAY, START_MONTH, START_YEAR, START_DATE, END_DAY, END_MONTH, END_YEAR)


View(mh_finalgtf)
