##CAR CLOSURES AND AGGREGATES TESTS##

#ISOLATING CAR FMP
MH_CARsort <- mh_sort %>%
  filter(FMP == "REEF FISH FISHERY OF PUERTO RICO AND THE U.S. VIRGIN ISLANDS")

expand_mhCARsort <- MH_CARsort %>%
  filter(SPP_TYPE == "SPECIES_GROUP", 
         MANAGEMENT_TYPE_USE %in% c("CLOSURE", "FISHING SEASON", "ALLOWABLE SPECIES", "POSSESSION LIMIT"))

