##CAR CLOSURES AND AGGREGATES TESTS##
#veiw all mng types
mh_sort %>% distinct(MANAGEMENT_TYPE_USE)

#ISOLATING CAR FMP
MH_CARsort <- mh_sort %>%
  filter(FMP == "REEF FISH FISHERY OF PUERTO RICO AND THE U.S. VIRGIN ISLANDS")

#CAR aggregates and closures
MH_CARsort %>% filter(SPP_TYPE %in% c("SPECIES_GROUP","SPECIES_AGGREGATE", "COMMON_NAME"),
         MANAGEMENT_TYPE_USE %in% c("CLOSURE", "FISHING SEASON", "ALLOWABLE SPECIES", "POSSESSION LIMIT"))%>%
  select(CLUSTER, STATUS_TYPE, MANAGEMENT_TYPE_USE, MANAGEMENT_STATUS_USE, SECTOR, SUBSECTOR_USE, ZONE, SECTOR_ID) %>%
  distinct(ZONE)

#sort closures by zone and species
MH_CARsort %>% filter(MANAGEMENT_TYPE_USE %in% c("CLOSURE", "FISHING SEASON", "ALLOWABLE SPECIES", 
                                                 "POSSESSION LIMIT", "PERMIT MORATORIUM", "LIMITED SPECIES"))%>%
  select(SECTOR_ID, vol, page, CLUSTER, STATUS_TYPE, MANAGEMENT_STATUS_USE, MANAGEMENT_TYPE_USE, 
         VALUE, diff ,diff_days, EFFECTIVE_DATE, START_DATE, CHANGE_DATE, END_DATE, SECTOR_USE, SPP_NAME, SPP_TYPE )%>%
  arrange(STATUS_TYPE, MANAGEMENT_STATUS_USE, desc(START_DATE), desc(vol), desc(page))%>%
  distinct(CLUSTER)
    
View(MH_CARsort)

test = filter(mh_sort, CLUSTER %in% c(713, 714, 1981, 1982, 1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991,
                                      1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000,  2001, 2002, 2003, 2004, 1440, 1441, 
                                      2046, 2049, 2050, 2051, 2052, 2053, 2054, 2048, 2055, 2047, 800, 801, 
                                      802, 803, 1021, 1022, 796, 795, 39, 40, 100, 101, 165))
select(test, SECTOR_ID, vol, page, CLUSTER, STATUS_TYPE, MANAGEMENT_STATUS_USE, MANAGEMENT_TYPE_USE, 
       VALUE, diff ,diff_days, EFFECTIVE_DATE, START_DATE, CHANGE_DATE,   END_DATE, SECTOR_USE, ZONE, SPP_NAME) %>%
  arrange(STATUS_TYPE, MANAGEMENT_STATUS_USE, desc(START_DATE), desc(vol), desc(page))
View(test)

##NOW FOR JUST AGG closures
MH_CARsort %>% filter(SPP_TYPE %in% c("SPECIES_GROUP","SPECIES_AGGREGATE"),
                      MANAGEMENT_TYPE_USE %in% c("CLOSURE", "FISHING SEASON", "ALLOWABLE SPECIES", "POSSESSION LIMIT"))%>%
  select(CLUSTER, STATUS_TYPE, MANAGEMENT_TYPE_USE, MANAGEMENT_STATUS_USE, 
         SECTOR, SUBSECTOR_USE, ZONE, SECTOR_ID)%>%
  distinct(ZONE)

view(MH_CARsort)

#agg closures only impact puerto rico managmenet area, 
#St. tomas/St. john managment area, and S.t croix managment area
#ALL AGG CLOSURES ARE ONCE

##AGG ALL MNG TYPES
MH_CARsort %>% filter(SPP_TYPE %in% c("SPECIES_GROUP","SPECIES_AGGREGATE"))%>%
  select(CLUSTER, STATUS_TYPE, MANAGEMENT_TYPE_USE, MANAGEMENT_STATUS_USE, SECTOR, SUBSECTOR_USE, ZONE, SECTOR_ID) %>%
  distinct(MANAGEMENT_TYPE_USE)
#aggs only impact fishing season, ACL, bag limit, and closure

#how many closures for CAR
MH_CARsort %>% filter(SPP_TYPE %in% c("SPECIES_GROUP","SPECIES_AGGREGATE", "COMMON_NAME"),
                      MANAGEMENT_TYPE_USE %in% c("CLOSURE", "FISHING SEASON", "ALLOWABLE SPECIES", "POSSESSION LIMIT"))%>%
  select(CLUSTER, STATUS_TYPE, MANAGEMENT_TYPE_USE, MANAGEMENT_STATUS_USE, SECTOR, SUBSECTOR_USE, ZONE, SECTOR_ID) %>%
  distinct(CLUSTER)
#51 distinct clusters
#INCORRECT, IT KEEPS INCLUDING DEFINITION RECORDS?? MAYBE NOT INCORRECT HOLD ON

##NOW JUST REC
MH_CARsort %>% filter(SPP_TYPE %in% c("SPECIES_GROUP","SPECIES_AGGREGATE", "COMMON_NAME"),
                      MANAGEMENT_TYPE_USE %in% c("CLOSURE", "FISHING SEASON", "ALLOWABLE SPECIES", "POSSESSION LIMIT"),
                      SECTOR == "RECREATIONAL")%>%
  select(CLUSTER, STATUS_TYPE, MANAGEMENT_TYPE_USE, MANAGEMENT_STATUS_USE, SECTOR, SUBSECTOR_USE, ZONE, SECTOR_ID) %>%
  distinct(CLUSTER)
#796, 2046, 2048, 2049, 2050, 2051
test = filter(mh_sort, CLUSTER %in% c(796, 2046, 2048, 2049, 2050, 2051))
select(test, SECTOR_ID, vol, page, CLUSTER, STATUS_TYPE, MANAGEMENT_STATUS_USE, MANAGEMENT_TYPE_USE, 
       VALUE, diff ,diff_days, EFFECTIVE_DATE, START_DATE, CHANGE_DATE,   END_DATE, SECTOR_USE, ZONE, SPP_NAME) %>%
  arrange(STATUS_TYPE, MANAGEMENT_STATUS_USE, desc(START_DATE), desc(vol), desc(page))
View(test)
#ALL REC AGG CLOSURES FALL WITHIN PUERTO RICO MNGT AREA
#1 SEASONAL CLOSURE, REMAINING ARE ONE TIME CLOSURES
#ALL ARE FOR SPECIES GROUPS, NO SINGULAR SPECIES CLOSURES

##NOW JUST COM
MH_CARsort %>% filter(SPP_TYPE %in% c("SPECIES_GROUP","SPECIES_AGGREGATE", "COMMON_NAME"),
                      MANAGEMENT_TYPE_USE %in% c("CLOSURE", "FISHING SEASON", "ALLOWABLE SPECIES", "POSSESSION LIMIT"),
                      SECTOR == "COMMERCIAL")%>%
  select(CLUSTER, STATUS_TYPE, MANAGEMENT_TYPE_USE, MANAGEMENT_STATUS_USE, SECTOR, SUBSECTOR_USE, ZONE, SECTOR_ID) %>%
  distinct(CLUSTER)
# 100, 101, 165, 795, 2047, 2052, 2053, 2054, 2055
test = filter(mh_sort, CLUSTER %in% c(100, 101, 165, 795, 2047, 2052, 2053, 2054, 2055))
select(test, SECTOR_ID, vol, page, CLUSTER, STATUS_TYPE, MANAGEMENT_STATUS_USE, MANAGEMENT_TYPE_USE, 
       VALUE, diff ,diff_days, EFFECTIVE_DATE, START_DATE, CHANGE_DATE,   END_DATE, SECTOR_USE, ZONE, SPP_NAME) %>%
  arrange(STATUS_TYPE, MANAGEMENT_STATUS_USE, desc(START_DATE), desc(vol), desc(page))
View(test)
#1 FISHING SEASON, REST ARE ONE TIME CLOSURES
#SPECIES GROUPS AND "SPECIES ALL"
#NO REOPENINGS

##now look at closures for "all species"
MH_CARsort %>% filter(SPP_NAME == "ALL",
                      MANAGEMENT_TYPE_USE %in% c("CLOSURE", "FISHING SEASON", "ALLOWABLE SPECIES", "POSSESSION LIMIT"),
                      SECTOR == "COMMERCIAL")%>%
  select(CLUSTER, STATUS_TYPE, MANAGEMENT_TYPE_USE, MANAGEMENT_STATUS_USE, SECTOR, SUBSECTOR_USE, ZONE, SECTOR_ID) %>%
  distinct(CLUSTER)
#100, 101, 165
test = filter(mh_sort, CLUSTER %in% c(100, 101, 165))
select(test, SECTOR_ID, vol, page, CLUSTER, STATUS_TYPE, MANAGEMENT_STATUS_USE, MANAGEMENT_TYPE_USE, 
       VALUE, diff ,diff_days, EFFECTIVE_DATE, START_DATE, CHANGE_DATE,   END_DATE, SECTOR_USE, SPP_NAME) %>%
  arrange(STATUS_TYPE, MANAGEMENT_STATUS_USE, desc(START_DATE), desc(vol), desc(page))
View(test)
#VARIETY OF CLOSED ZONES
#ALL ONE TIME CLOSURES

#AGG SPECIFIC CLOSURES?
MH_CARsort %>% filter(SPP_TYPE == "SPECIES_AGGREGATE",
                      MANAGEMENT_TYPE_USE %in% c("CLOSURE", "FISHING SEASON", 
                                                 "ALLOWABLE SPECIES", "POSSESSION LIMIT"))%>%
  select(CLUSTER, STATUS_TYPE, MANAGEMENT_TYPE_USE, MANAGEMENT_STATUS_USE, SECTOR, SUBSECTOR_USE, ZONE, SECTOR_ID) %>%
  distinct(CLUSTER)
#NO OG AGGS IN CLOSURES

##investigate fishery year real fast
test <- mh_sort %>% filter(MANAGEMENT_TYPE_USE == "FISHING YEAR")%>%
  select(CLUSTER,REGULATION_ID, STATUS_TYPE, MANAGEMENT_TYPE_USE, MANAGEMENT_STATUS_USE, SECTOR, FMP, SUBSECTOR_USE, 
         ZONE, EFFECTIVE_DATE, START_DATE, START_DAY, START_MONTH, START_YEAR, CHANGE_DATE, END_DAY, END_MONTH,
         END_YEAR, END_DATE, SECTOR_USE, SPP_NAME, SECTOR_ID)
view(test)
#INVESTIGATE REG ID 2092 AND 2103 (CLUSTERS 678 AND 698)
test = filter(mh_sort, CLUSTER == 698)
select(test, SECTOR_ID, vol, page, CLUSTER, STATUS_TYPE, MANAGEMENT_STATUS_USE, MANAGEMENT_TYPE_USE, 
       VALUE, diff ,diff_days, EFFECTIVE_DATE, START_DATE, CHANGE_DATE,   END_DATE, SECTOR_USE, SPP_NAME) %>%
  arrange(STATUS_TYPE, MANAGEMENT_STATUS_USE, desc(START_DATE), desc(vol), desc(page))
View(test)
#fishing year march 1 - march 1 because its for march 1 thru end of feb
test = filter(mh_sort, CLUSTER == 678)
select(test, SECTOR_ID, vol, page, CLUSTER, STATUS_TYPE, MANAGEMENT_STATUS_USE, MANAGEMENT_TYPE_USE, 
       VALUE, diff ,diff_days, EFFECTIVE_DATE, START_DATE, CHANGE_DATE,   END_DATE, SECTOR_USE, SPP_NAME) %>%
  arrange(STATUS_TYPE, MANAGEMENT_STATUS_USE, desc(START_DATE), desc(vol), desc(page))
View(test)

#2103 = BLACK SEA BASS IN SASG - no closure component for adjustment to fishing year
test2 = filter(mh_sort, MANAGEMENT_TYPE_USE == "CLOSURE", 
              FMP == "SNAPPER-GROUPER FISHERY OF THE SOUTH ATLANTIC REGION",
              SECTOR_USE == "COMMERCIAL",
              SPP_NAME %in% c("ALL", "BASS, BLACK SEA"))
select(test2, SECTOR_ID, vol, page, CLUSTER, STATUS_TYPE, MANAGEMENT_STATUS_USE, MANAGEMENT_TYPE_USE, 
       VALUE, diff ,diff_days, EFFECTIVE_DATE, START_DATE, CHANGE_DATE,   END_DATE, SECTOR_USE, SPP_NAME) %>%
  arrange(STATUS_TYPE, MANAGEMENT_STATUS_USE, desc(START_DATE), desc(vol), desc(page))
View(test2)

#CAR bag limits
MH_CARsort %>% filter(MANAGEMENT_TYPE_USE == "BAG LIMIT")%>%
  select(CLUSTER, STATUS_TYPE, MANAGEMENT_TYPE_USE, MANAGEMENT_STATUS_USE, SECTOR, SUBSECTOR_USE, ZONE, SECTOR_ID) %>%
  distinct(CLUSTER)
#BAG LIMITS ARE SIMPLE, ZERO ADJUSTMENTS
test = filter(mh_sort, CLUSTER %in% c(1770, 1771, 2036, 2037))
select(test, SECTOR_ID, vol, page, CLUSTER, STATUS_TYPE, MANAGEMENT_STATUS_USE, MANAGEMENT_TYPE_USE, 
       VALUE, diff ,diff_days, EFFECTIVE_DATE, START_DATE, CHANGE_DATE,   END_DATE, SECTOR_USE, SPP_NAME) %>%
  arrange(STATUS_TYPE, MANAGEMENT_STATUS_USE, desc(START_DATE), desc(vol), desc(page))
View(test)
#ALL BAG LIMITS ARE AGGREGATES, NO SIMPLE SPECIES

#CAR SIZE LIMITS
MH_CARsort %>% filter(MANAGEMENT_TYPE_USE == "MINIMUM SIZE LIMIT")%>%
  select(CLUSTER, STATUS_TYPE, MANAGEMENT_TYPE_USE, MANAGEMENT_STATUS_USE, SECTOR, SUBSECTOR_USE, ZONE, SECTOR_ID) %>%
  distinct(CLUSTER)
#9 SPECIES, NO AGGS, SIMPLE
test = filter(mh_sort, CLUSTER %in% c(1162, 1163, 1166, 1167, 1178, 1179, 1180, 1181, 1182, 
                                      1183, 1184, 1185, 1186, 1187, 1188, 1189, 1190, 1191))
select(test, SECTOR_ID, vol, page, CLUSTER, STATUS_TYPE, MANAGEMENT_STATUS_USE, MANAGEMENT_TYPE_USE, 
       VALUE, diff ,diff_days, EFFECTIVE_DATE, START_DATE, CHANGE_DATE,   END_DATE, SECTOR_USE, SPP_NAME) %>%
  arrange(STATUS_TYPE, MANAGEMENT_STATUS_USE, desc(START_DATE), desc(vol), desc(page))
View(test)
