## MH_PRE_PROCESS.R TESTS ------

##SUBSECTOR FORKS ----
# TEMPORARY TEST WHILE WE PREPARE THE CODE IN MH_PRE_PROCESS.R TO INCLUDE
# ALL FMPS. PROVIDES SUBSECTOR INFORMATION INCLUDING SECTOR ID, 
# START DATE OF USE, AND COUNTS RELATED TO THE SUBSECTOR TO INVESTIGATE 
# SUBSECTOR FORKS AND DETERMINE HOW TO BEST ADDRESS THEM
quick_look <- multi_subsector_key %>%
  filter(FMP == "SNAPPER-GROUPER FISHERY OF THE SOUTH ATLANTIC REGION") 

# CREATES THE FIELDS OF EXPAND_FROM, EXPAND_TEMP, AND EXPAND_TO
# TO ADDRESS SITATUATIONS WHERE "ALL" IS ONE OF THE SUBSECTORS.
# SUBSECTORS WITH "MANUAL CHECK IN THE EXPAND_TO FIELD SHOULD BE ADDRESSED
expand_sector_keys_recGOMRF <- multi_subsector_key %>%
  filter(FMP == "REEF FISH RESOURCES OF THE GULF OF MEXICO",
         SECTOR_USE == "RECREATIONAL") %>%
  select(SECTOR_ID, SECTOR_USE, SUBSECTOR_KEY, subsector_all_used) %>%
  distinct() %>%
  mutate(column_name = "SUBSECTOR",
         expand_from = case_when(subsector_all_used == 1 ~ "ALL"),
         expand_temp = str_remove(SUBSECTOR_KEY, paste0(expand_from, ", ")),
         expand_to = case_when(str_count(expand_temp, ',') >= 1 ~ expand_temp,
                               TRUE ~ "MANUAL CHECK"))

# EXAMPLE OF ADDRESSING MANUAL CHECK VALUES WITHIN THE EXPAND_TO FIELD.
# BY REMOVING VARIABLES (ZONE AND MANAGEMENT_STATU) FROM THE CLUSTER MATCH,
# WE REDUCED MANAUL FORKS FOR GOM (WILL NEED MANUAL CHECK FOR OTHER FMPS)
 expand_sector_keys_recGOMRF_use <- expand_sector_keys_recGOMRF %>%
   mutate(expand_to = case_when(SECTOR_ID == 1110 ~ "FOR-HIRE, PRIVATE",
                                TRUE ~ expand_to))

# CREATE AN EXPANSIONS DATA FRAME TO JOIN TO MH_SECTOR_ID.
# THIS IS WHERE WE HAD BROKEN THE CODE WE TURNED OFF THE CODE ABOVE 
# BUT FORGOT THAT THE OBJECT ALREADY EISTED IN OUR ENVIRONMENT
#expansions <- expand_sector_keys_recGOMRF_use
expansions <- expand_sector_keys_recGOMRF
 
## MH_PROCESS.R TESTS ------

## CLOSURE TESTS ----
# INVESTIGATING RECREATIONAL CLOSURES FOR RED GROUPER TO CREATE
# A COMPREHENSIVE AND CLEAR TIME SERIES OF CLOSURES
mh_sort %>% filter(SPP_NAME == c("GROUPER, RED", "CLOSURE/REOPENING: SHALLOW-WATER GROUPER (SWG)", "CLOSURE/REOPENING: GROUPERS"),
                   FMP == "REEF FISH RESOURCES OF THE GULF OF MEXICO",
                   MANAGEMENT_TYPE_USE %in% c("CLOSURE", "FISHING SEASON", "ALLOWABLE SPECIES", "POSSESSION LIMIT")) %>% 
  select(CLUSTER, STATUS_TYPE, MANAGEMENT_TYPE_USE, MANAGEMENT_STATUS_USE, SECTOR, SUBSECTOR_USE, ZONE, SECTOR_ID) %>%
  distinct(CLUSTER)

# TEST TO INVESTIGATE CLUSTERS RELATED TO CLOSURES TO MAKE SURE THAT 
# THE TIME SERIES IS COMPREHENSIVE AND ACCURATE.
test = filter(mh_sort, CLUSTER %in% c(1419, 1424, 1012, 2102, 2103))
select(test, SECTOR_ID, vol, page, CLUSTER, STATUS_TYPE, MANAGEMENT_STATUS_USE, MANAGEMENT_TYPE_USE,
       VALUE, diff ,diff_days, EFFECTIVE_DATE, START_DATE, CHANGE_DATE,   END_DATE, SECTOR_USE, SPP_NAME) %>%
  arrange(STATUS_TYPE, MANAGEMENT_STATUS_USE, desc(START_DATE), desc(vol), desc(page))

write.csv(test, "redsnapper_closure_clusters.csv")

# TESTS TO INVESTIGATE RECREATIONAL RECURRING CLOSURES BY SECTOR TO MAKE 
# SURE THE TIME SERIES IS COMPREHENSIVE AND ACCURATE. THESE INCLUDE 
# SEASONAL, WEEKLY, AND MONTHLY RECURRING RECORDS.
test2 = filter(test, STATUS_TYPE == "RECURRING", SECTOR_USE == "RECREATIONAL")
select(test2, vol, page, CLUSTER, MANAGEMENT_STATUS_USE, MANAGEMENT_TYPE_USE,
       VALUE, diff ,diff_days, EFFECTIVE_DATE, START_DATE, CHANGE_DATE, END_DATE, SUBSECTOR_USE) %>%
  arrange(SUBSECTOR_USE, MANAGEMENT_STATUS_USE, desc(START_DATE), desc(vol), desc(page))

# TESTS TO INVESTIGATE COMMERCIAL RECURRING CLOSURES BY SECTOR TO MAKE 
# SURE THE TIME SERIES IS COMPREHENSIVE AND ACCURATE. THESE INCLUDE 
# SEASONAL, WEEKLY, AND MONTHLY RECURRING RECORDS.
test = filter(mh_sort, CLUSTER %in% c(20, 369, 410,482, 826, 827, 1330))
test3 = filter(test, STATUS_TYPE == "RECURRING", SECTOR_USE == "COMMERCIAL")%>%
  arrange(MANAGEMENT_STATUS_USE, desc(START_DATE), desc(vol), desc(page))
select(test3, vol, page, CLUSTER, MANAGEMENT_STATUS_USE,
       diff ,diff_days, EFFECTIVE_DATE, INEFFECTIVE_DATE, START_DATE, 
       CHANGE_DATE, END_DATE, START_MONTH, START_DAY, END_MONTH, END_DAY) 

# TESTS TO INVESTIGATE RECREATIONAL ONE TIME CLOSURES TO MAKE SURE THE 
# TIME SERIES IS COMPREHENSIVE AND ACCURATE.
test = filter(mh_sort, CLUSTER %in% c(20, 369, 410,482, 826, 827, 1330))
test4 = filter(test, SECTOR_USE == "RECREATIONAL", MANAGEMENT_STATUS_USE  == "ONCE", MANAGEMENT_TYPE_USE == "CLOSURE") %>%
  arrange(SUBSECTOR_USE, MANAGEMENT_TYPE_USE, MANAGEMENT_STATUS_USE, desc(START_DATE), desc(vol), desc(page))
select(test4, ZONE_USE, vol, page,
       VALUE,diff_days, NEVER_IMPLEMENTED, EFFECTIVE_DATE, INEFFECTIVE_DATE, START_DATE, CHANGE_DATE, END_DATE1, END_DATE, SUBSECTOR_USE)[40:52,]

## MINIMUM SIZE LIMIT TESTS ----
# TEST TO INVESTIGATE RED SNAPPER RECREATIONAL MINIMUM SIZE LIMIT RECORDS 
# TO MAKE SURE THAT THE TIME SERIES IS COMPREHENSIVE AND ACCURATE.
test = filter(mh_sort, CLUSTER == 1733)
select(test, ID,vol, page, MANAGEMENT_STATUS_USE, SECTOR_USE, ADJUSTMENT, MANAGEMENT_TYPE_USE, END_MONTH, VALUE, diff ,diff_days, EFFECTIVE_DATE, START_DATE, CHANGE_DATE,   END_DATE, NEVER_IMPLEMENTED) %>%
  arrange(STATUS_TYPE, MANAGEMENT_STATUS_USE, desc(START_DATE), desc(vol), desc(page))

# TEMPORARY FIX TO CREATE AN ADJUSMENT IN CLUSTER 1733 SO THAT THE DATES 
# IN THE TIME SERIES LINE UP CORRECTLY.
mh_detect <- mh_detect %>%
  mutate(ADJUSTMENT = case_when(REGULATION_ID == 792 ~ 1,
                                TRUE ~ ADJUSTMENT))

# TEST TO INVESTIGATE RED SNAPPER COMMERCIAL MINIMUM SIZE LIMIT RECORDS 
# TO MAKE SURE THAT THE TIME SERIES IS COMPREHENSIVE AND ACCURATE.
test = filter(mh_sort, CLUSTER == 1304)
select(test, vol, page, CLUSTER, SECTOR_USE, ADJUSTMENT, MANAGEMENT_TYPE_USE, VALUE, VALUE_RATE, diff ,diff_days, EFFECTIVE_DATE, START_DATE, CHANGE_DATE,   END_DATE, NEVER_IMPLEMENTED)

## BAG LIMIT TESTS ----
# TEST TO INVESTIGATE RED SNAPPER RECREATION BAG LIMIT RECORDS
# TO MAKE SURE THAT THE TIME SERIES IS COMPREHENSIVE AND ACCURATE.
test = filter(mh_sort, CLUSTER == 1305)
select(test, vol, page, CLUSTER, SECTOR_USE, ADJUSTMENT, VALUE, VALUE_RATE, diff ,diff_days, EFFECTIVE_DATE, START_DATE, CHANGE_DATE,   END_DATE, NEVER_IMPLEMENTED)

## CLUSTER INVESTIGATION ----
# CLUSTER 14 - DEALT WITH 14 (BAG LIMIT NEEDS TO BE FOR GOLIATH ALONE 0)
#   - AGGREGATE GROUPER BAG LIMIT WILL BE REMOVED WITH BUG ID 6606
#     WHICH SHOULD SOLVE THE ISSUE WITH THIS CLUSTER
#
# CLUSTER 518 - 518 is a fishing year (new policy, fishing year does not get start year) 
# 
# CLUSTERS 542, 543, 544, 545 - THERE ARE ONLY 21 TIMES WHEN START DATE IS BEFORE EFFECTIVE DATE
# POTENTIAL NEW RULE - IF START DATE IS BEFORE EFFECTIVE DATE; KEEP EFFECTIVE DATE 
# 
# CLUSTERS 1751, 1812 - Keep thinking about how open and closed value affects the sorting

# start day month, year, have their own meaning 
# (effective date should not be overwritten in this case)
# write check for start date happening before effective date (that should not be a thing)
# FOR "FISHING YEAR"(change to reoccurring?)
# COULD TREAT DATES LIKE VALUES FOR CERTAIN MANAGEMENT TYPES (EX ACL, AND FISHING YEAR)

# CONSIDER ADDING DECIMAL YEAR SUMMARY
# DECIMAL_START_YEAR = decimal_date(as.POSIXlt(START_DATE))
# DECIMAL_END_YEAR = decimal_date(as.POSIXlt(END_DATE))

## INITIAL CODE CREATED TO INVESTIGATE CLUSTERS RELATING TO GULF REEF FISH.
# Export for reviewing results for Gulf Reef Fish (SFA)
# mh_redundant_GOMRF <- mh_detect %>%
#   filter(REDUNDANT == 1, FMP == 'REEF FISH RESOURCES OF THE GULF OF MEXICO')
# mh_gulf_reef_review <- mh_sort2 %>% filter(FMP == 'REEF FISH RESOURCES OF THE GULF OF MEXICO') %>%
#   bind_rows(., mh_redundant_GOMRF) %>%
#   select(., REGION, REGULATION_ID, FR_CITATION, SECTOR_USE, SUBSECTOR, MANAGEMENT_CATEGORY, MANAGEMENT_TYPE, MANAGEMENT_STATUS, ZONE_USE,
#          SPP_NAME, COMMON_NAME_USE, EFFECTIVE_DATE, INEFFECTIVE_DATE,
#          START_DAY_RECURRING, START_MONTH_RECURRING, START_TIME_RECURRING, START_DAY_OF_WEEK_RECURRING,
#          END_DAY_RECURRING, END_MONTH_RECURRING, END_TIME_RECURRING, END_DAY_OF_WEEK_RECURRING,
#          MANAGEMENT_TYPE_USE, MANAGEMENT_STATUS_USE, CLUSTER, COLLECTION, GENERAL, COMPLEX,
#          VALUE, VALUE_UNITS, VALUE_TYPE, VALUE_RATE,
#          REG_CHANGE, MULTI_REG, MULTI_REG_CLUSTER, REG_REMOVED, REDUNDANT, NEVER_IMPLEMENTED, diff, diff_days, CHANGE_DATE,
#          vol, page, START_DATE, END_DATE, IMP_START_DATE, IMP_END_DATE) %>%
#   arrange(., CLUSTER, START_DATE, vol, page)
# 
# write.csv(mh_sort2, paste0("./Output/MHprocessed_clean_", format(Sys.Date(), "%d%b%Y"), ".csv"), row.names = FALSE)







